services:
  - type: web
    name: api-gestao-crosby
    runtime: node
    rootDir: backend
    buildCommand: npm install
    startCommand: node index.js
    envVars:
      - key: NODE_ENV
        value: production
